const chapters = [
  "0.Basic Maths",
  "1.U & D",
  "2.Kinematics",
  "3.NLM",
  "4.WPE",
  "5.Circular ",
  "6.COM ",
  "7.Rotation",
  "8.Gravitation",
  "9.Elasticity",
  "10.Fluids",
  "11.SHM",
  "12.String Waves",
  "13.Sound Waves",
  "14.Thermal Physics",
  "15.KTG",
  "16.Thermodynamics",
  "17.Electrostatics ",
  "18.Capacitance",
  "19.Current Electricity",
  "20.Magnetism",
  "21.EMI",
  "22.AC",
  "23.Ray Optics",
  "24.Wave Optics",
  "25.Modern Physics",
  "26.EM Waves",
  "27.Semiconductors",
  "28.Errors ",
];

export default chapters;